addSbtPlugin("com.eed3si9n"              % "sbt-assembly"  % "0.14.10")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.19")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"     % "1.4.8")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"  % "0.9.30")
